### ISSUE TITLE
Вывод скользящих и обычных средних для голов и рейтингов

### ISSUE THREAD

**Issue by SitnikovN** [SitnikovN/newrep#1]
![image](https://user-images.githubusercontent.com/49856322/105719747-b59f0300-5f33-11eb-9b0a-3b611dfc348c.png)

Нужен  запрос с выводом как на картинке. Дополнительно протянуть дату.
*m3 - трехматчевое среднее
mis - пропущенные
sc - забитые

**Comment by SitnikovN** [comment]
Заготовка , над которой ты работала:

_**with teams_goals as (
select
	mo.season, mo.match_date, t1.team_name home, t2.team_name away, mo.hs home_sc, mo.gs away_sc
from
	matches_old mo
join teams t1 on
	home_id = t1.team_id
join teams t2 on
	guest_id = t2.team_id 
where  mo.season = '16/17'
	and (t1.team_name = 'Arsenal'
	or t2.team_name= 'Arsenal')
	),
teams_results as (
select
	tg.season, 
	match_date, 
	tg.home, 
	tg.away, 
	home_sc, away_sc, home_val, away_val
from
	teams_goals tg
join fct_match_rait fmr on
	tg.season = fmr.season
	and tg.home = fmr.home
	and tg.away = fmr.away
	),
raw_piv_tb as (
select
	season,
	to_date(substring(match_date,1,10),'yyyy-mm-dd') m_date,
  	case when t1.home = t2.team_name then t1.home else t1.away end team,
  	case when t1.home = t2.team_name then t1.away else t1.home end enemy,
  	case when t1.home = t2.team_name then t1.home_sc else t1.away_sc end team_sc,
  	case when t1.home = t2.team_name then t1.away_sc else t1.home_sc end enemy_sc
from teams t2 
	join teams_results t1
	on t1.home = t2.team_name or t1.away = t2.team_name
)
select *
from raw_piv_tb
order by team,m_date asc**_

**Comment by SitnikovN** [comment]
_select  
      row_number() over(partition by team order by mdate asc) m_num
      ,team,enemy,team_val,enemy_val,team_sc,enemy_sc,
      --rait
      cast((avg(1.00*team_val) over(partition by team order by mdate asc
        rows between 3 preceding and 1 preceding)) as decimal(3,1)) m3_team_val,
      cast((avg(1.00*team_val) over(partition by team order by mdate asc
        rows between 6 preceding and 1 preceding)) as decimal(3,1)) m6_team_val,
      --goals m3
      cast((avg(1.00*team_sc) over(partition by team order by mdate asc
        rows between 3 preceding and 1 preceding)) as decimal(3,1)) m3_team_sc,
      cast((avg(1.00*enemy_sc) over(partition by team order by mdate asc
        rows between 3 preceding and 1 preceding)) as decimal(3,1)) m3_team_mis, 
      --goals m6 
      cast((avg(1.00*team_sc) over(partition by team order by mdate asc
        rows between 6 preceding and 1 preceding)) as decimal(3,1)) m6_team_sc,
      cast((avg(1.00*enemy_sc) over(partition by team order by mdate asc
        rows between 6 preceding and 1 preceding)) as decimal(3,1)) m6_team_mis, 
      team_sc - enemy_sc team_gl_diff,
      enemy_sc - team_sc enemy_gl_diff_

**Comment by SitnikovN** [comment]
> _select row_number() over(partition by team order by mdate asc) m_num ,team,enemy,team_val,enemy_val,team_sc,enemy_sc, --rait cast((avg(1.00_team_val) over(partition by team order by mdate asc rows between 3 preceding and 1 preceding)) as decimal(3,1)) m3_team_val, cast((avg(1.00_team_val) over(partition by team order by mdate asc rows between 6 preceding and 1 preceding)) as decimal(3,1)) m6_team_val, --goals m3 cast((avg(1.00_team_sc) over(partition by team order by mdate asc rows between 3 preceding and 1 preceding)) as decimal(3,1)) m3_team_sc, cast((avg(1.00_enemy_sc) over(partition by team order by mdate asc rows between 3 preceding and 1 preceding)) as decimal(3,1)) m3_team_mis, --goals m6 cast((avg(1.00_team_sc) over(partition by team order by mdate asc rows between 6 preceding and 1 preceding)) as decimal(3,1)) m6_team_sc, cast((avg(1.00_enemy_sc) over(partition by team order by mdate asc rows between 6 preceding and 1 preceding)) as decimal(3,1)) m6_team_mis, team_sc - enemy_sc team_gl_diff, enemy_sc - team_sc enemy_gl_diff_

вот так делаются скользящие)) через выражение 
**_rows between 3 preceding and 1 preceding_**

это синтаксис из sql server, тебе надо переделать на postgres

4.2.8. Window Function Calls
https://www.postgresql.org/docs/9.1/sql-expressions.html

**Comment by maria-pet** [comment]
Привет

**Comment by SitnikovN** [comment]
Дополнительно есть справка на русском у sql server'a:
https://docs.microsoft.com/ru-ru/sql/t-sql/queries/select-over-clause-transact-sql?view=sql-server-ver15

**Comment by SitnikovN** [comment]
[vw_main_agg_analytics.txt](https://github.com/SitnikovN/newrep/files/5897679/vw_main_agg_analytics.txt)

**Comment by maria-pet** [comment]
Создано представление:
[vw_main_agg_analytics.txt](https://github.com/SitnikovN/newrep/files/5897680/vw_main_agg_analytics.txt)

**Comment by SitnikovN** [comment]
Молодец, вижу.
Задачку закрываю
