### ISSUE TITLE
Вывести список пропущенных матчей в таблице matches_old

### ISSUE THREAD

**Issue by SitnikovN** [SitnikovN/newrep#2]
В таблице **matches_old** не все матчи по сезонам, есть пропуски. Посчитать их относительно таблицы **fct_match_rait** ,
там более полные данные.

Вот пример кода, чтобы было яснее:
  _select *
  from (
  select 
	  season,home team,'home' place,count(*)
  from fct_match_rait 
  group by season ,home
  union all
  select 
	  season,away ,'away', count(*)
  from fct_match_rait 
  group by season ,away
  ) tb_

Если посчитать также матчи в **matches_old** их будет другое кол-во для большинства случаев, но всегда меньшее либо равно. Нужно вывести пропущенные матчи в формате : season|home|away

**Comment by maria-pet** [comment]
select
	fmr.season,
	fmr.home,
	fmr.away
from
	fct_match_rait fmr
left join vw_main_agg_analytics vmaggan on
	fmr.season = vmaggan.season
	and fmr.home = vmaggan.team
	and fmr.away = vmaggan.enemy
where
	vmaggan.season is null

**Comment by SitnikovN** [comment]
Good.
