### ISSUE TITLE
Исправление данных, догрузка отсутствующих матчей

### ISSUE THREAD

**Issue by SitnikovN** [SitnikovN/newrep#3]
Я прогрузил табличку **fct_full_match_results**. Там полный список матчей, как должно быть, без аномалий.
Для начала, я бы предложил переделать вьюшку **vw_main_agg_analytics**, использовать эту табличку вместо matches_old.

Команды уже в нужно формате, названия соответствуют, присоединять к teams не надо.
После того как поменяешь, должны уйти пропуски из матчей, но тебе это все надо будет проверять.
В итоге , допустим , для Арсенала, вьюшка должна будет вернуть 18 матчей дома и 18 в гостях всего 38.
Как раз-таки 38 матчей у них в fct_full_match_results, которую я прогрузил. 
Единственное - я закосячил с данными португальской лиги, поэтому их там нет в fct_full_match_results, догружу позже

**Comment by SitnikovN** [comment]
Создано представление 
[new_main_analytics.txt](https://github.com/SitnikovN/newrep/files/5936497/new_main_analytics.txt)
Вывести отсутствующие матчи:
select * from new_main_agg_analytics
where team_val is null

**Comment by maria-pet** [comment]
Создано представление
new_main_analytics.txt
Вывести отсутствующие матчи:
select * from new_main_agg_analytics
where team_val is null

**Comment by SitnikovN** [comment]
Почему вьюшка выводит этим матчи с пустым рейтингом?
_select * from new_main_agg_analytics
where team_val is null
and team = 'Atalanta'
and season = '18/19'
order by season,team,m_date asc_

Вообще, внутри вьюшки в стартовой cte матч с Миланом есть, почему он в конце пропадает?

SELECT ffmr.season,
            ffmr.mdate,
            ffmr.home,
            ffmr.away,
            ffmr.home_sc::integer AS home_sc,
            ffmr.away_sc::integer AS away_sc,
            fmr.home_val,
            fmr.away_val
           FROM fct_full_match_results ffmr
             LEFT JOIN fct_match_rait fmr ON ffmr.season::text = fmr.season::text 
             AND ffmr.home::text = fmr.home::text 
             AND ffmr.away::text = fmr.away::text
    where fmr.season = '18/19'
    and ffmr.home = 'Atalanta'

**Comment by SitnikovN** [comment]
В таблице fct_match_rait есть повторяющиеся матчи, но с разным рейтингом. Обычно они различаются на несколько сотых. Можно принять их за дубликаты.  Найти все такие матчи и удалить дубликаты.

![image](https://user-images.githubusercontent.com/49856322/107145753-c482ae00-6954-11eb-8422-be626e3e718f.png)

**Comment by SitnikovN** [comment]
> Создано представление
> new_main_analytics.txt
> Вывести отсутствующие матчи:
> select * from new_main_agg_analytics
> where team_val is null

---------------------
Я удалил старую вьюшку, которая с прямым джойном. Оставил одну, и переименовал.
Часть данных, которые вылетала как результат селекта, я почистил. Теперь их намного меньше.
Остальные матчи реально отсутствуют, я их буду догружать вручную наверно)

**Comment by maria-pet** [comment]
Найдены дубликаты (их 58), отсортировала по убыванию в части delta_home, проверь, пожалуйста, первую строку (максимальное отклонение по модулю - 0,11),  в delta_away отклонения до 0,1. После проверки строки удалю
[doubling.txt](https://github.com/SitnikovN/newrep/files/5975450/doubling.txt)

**Comment by maria-pet** [comment]
Удалено 58 дубликатов:
delete from fct_match_rait fmr using doubling d
      where concat (fmr.season, ' ',fmr.home, ' ',fmr.away, ' ',fmr.home_val, ' ',fmr.away_val)=
       concat (d.season, ' ',d.home, ' ',d.away, ' ',d.home_val, ' ',d.away_val)
