### ISSUE TITLE
Добавление столбцов стриков во вьюшку

### ISSUE THREAD

**Issue by SitnikovN** [SitnikovN/newrep#4]
Добавить в основную вьюшку столбцы стриков по победам, матчам с рейтингом больше 7.
Пример алгоритма:

with aaa as
	(
	select 
		match_date,
		case 
			when t1.guest = 'Милан'
			   then case when guest_sc>0 then 1 else 0 end 
			when t1.home = 'Милан'
			   then case when home_sc>0 then 1 else 0 end
		end is_scored
	from matches_prcd t1
	where season='17/18' and
		(guest = 'Милан' or home = 'Милан' )  
	)
select
			is_scored,
			diff,
			min(match_date) st_date,
			max(match_date) end_date,
			count(*) match_num
		from
			(
				select match_date,
								is_scored,
								ROW_NUMBER() over(order by match_date)-
									ROW_NUMBER() over(partition by is_scored order by match_date) diff		
				from aaa
			) t
		group by 
			is_scored,
			diff
		order by end_date asc

2017-08-20 00:00:00.000	1	1	1
2017-08-27 00:00:00.000	1	2	2
2017-09-10 00:00:00.000	1	3	3
2017-09-17 00:00:00.000	1	4	4
2017-09-20 00:00:00.000	1	5	5
2017-09-24 00:00:00.000	0	6	1
2017-10-01 00:00:00.000	0	7	2

**Comment by maria-pet** [comment]
создано 2 функции:
win_lose_streak
val_7_streak
